### ISSUE TITLE
Scribe java fork is not available!

### ISSUE THREAD

**Issue by rcleps** [stackmagic/bitly-api-client#11]
the link https://github.com/stackmagic/scribe-java is not available!

**Comment by stackmagic** [comment]
You are right - I deleted this some time ago but found it somewhere and resurrected it...
Mind you, this is really old. It was once forked from https://github.com/scribejava/scribejava

Maybe you don't even need it anymore, you can get a "generic access token" from from the bitly website when logged in click the menu on the top right then on your user name and there's "generic access token"

**Comment by stackmagic** [comment]
repo: https://github.com/stackmagic/scribe-java
