### ISSUE TITLE
Upgrade for v4

### ISSUE THREAD

**Issue by aburnett** [stackmagic/bitly-api-client#14]
Opening this issue mainly as a starting point for discussion around supporting bitly api v4. Are there any plans to create a new release of this library centered around v4?

**Comment by stackmagic** [comment]
No I don't have any plans for a version upgrade because I don't use it anymore. You'd have to do a v4 implementation yourself. Feel free to fork or even publish a new lib on your own, I'll happily link to your repo and retire this project.
